### 数据抽样

In [2]:
# 使用random实现抽样处理
import random
import numpy as np

In [5]:
# 采用random的sample方法进行简单随机抽样
data = np.loadtxt('../dataset/data3.txt')
simple_randpm_resampled = data[random.sample([i for i in range(len(data))], 2000)]    # 样本大小
print(len(simple_randpm_resampled))
# simple_randpm_resampled[:5]

2000


In [6]:
# 等距抽样
sample_count = 2000
record_count = data.shape[0]
width = record_count / sample_count
equidistant_resampled = []
i = 0    # 自增计数以得到对应索引值
while len(equidistant_resampled) <= sample_count and i*width <= record_count-1:    # 当样本量<=指定抽样数量，且矩阵索引在有效范围内时
    equidistant_resampled.append(data[int(i * width)])
    i += 1
print(len(equidistant_resampled))
equidistant_resampled[:5]

2000


[array([-3.08057779,  8.09020329,  2.02732982,  2.92353937, -6.06318211]),
 array([-2.11984871,  7.74916701,  5.7318711 ,  4.75148273, -5.68598747]),
 array([-1.32948128,  8.11607819,  5.47467426,  2.26973107, -7.91745707]),
 array([-1.35101097,  9.271403  ,  4.95439173,  3.34503182, -6.7040739 ]),
 array([-2.40684994,  8.58167685,  3.98069653,  1.97710699, -6.40187309])]

In [19]:
# 分层抽样
data_stratified = np.loadtxt('../dataset/data2.txt')
each_sample_count = 50    # 定义每个分层的抽样数量
label_data_unique = np.unique(data_stratified[:, -1])    # 定义分层值域
stratified_resampled = []
stratified_dict = {}
for label_data in label_data_unique:
    sample_list = []
    for data_tmp in data_stratified:
        if data_tmp[-1] == label_data:
            sample_list.append(data_tmp)
    each_sample_data = random.sample(sample_list,
                                     each_sample_count)
    stratified_resampled.extend(each_sample_data)
    stratified_dict[label_data] = len(each_sample_data)

print(stratified_dict)

{0.0: 50, 1.0: 50}


In [26]:
# 整群抽样
data_cluster = np.loadtxt('../dataset/data4.txt')
label_data_unique = np.unique(data_cluster[:, -1])    # 统计数据中有几个整群
print(label_data_unique)    
sample_label = random.sample(set(label_data_unique), 2)    # 随机抽取两个整群
cluster_resampled = []
for each_label in sample_label:
    for data_tep in data_cluster:
        if data_tep[-1] == each_label:
            cluster_resampled.append(data_tep)
print(sample_label)
print(len(cluster_resampled))

[0. 1. 2. 3.]
[1.0, 0.0]
500
