In [5]:
from math import exp
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [6]:
x = np.arange(15).reshape(5, 3)
data_mat = []
for d in x:
    data_mat.append([1.0, *d])

weights = np.zeros((len(data_mat[0]), 1), dtype=np.float32)

np.mat(data_mat)

matrix([[ 1.,  0.,  1.,  2.],
        [ 1.,  3.,  4.,  5.],
        [ 1.,  6.,  7.,  8.],
        [ 1.,  9., 10., 11.],
        [ 1., 12., 13., 14.]])

In [7]:
np.zeros((4, 1))

array([[0.],
       [0.],
       [0.],
       [0.]])

In [8]:
import numpy as np

In [9]:
X = np.array([[-1, 1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
X.shape

(6, 2)

In [10]:
x_samples, x_features = X.shape
print("x_samples = {}, x_features = {}".format(x_samples,x_features))

x_samples = 6, x_features = 2


In [11]:
mean = np.array([np.mean(X[:, i]) for i in range(x_features)])
norm_x = X - mean
k = 1
#scatter matrix
scatter_matrix = np.dot(norm_x, np.transpose(norm_x))

#Calculate the eigenvectors and eigenvalues
eig_val, eig_vec = np.linalg.eig(scatter_matrix)
eig_pairs = [(np.abs(eig_val[i]), eig_vec[:, i]) for i in range(x_features)]

# sort eig_vec based on eig_val from highest to lowest, and select the top k eig_val
eig_pairs.sort(reverse = True)
eig_pairs

[(37.70674550364642,
  array([-0.08292   +0.j, -0.39108846+0.j, -0.61478874+0.j,  0.19554423+0.j,
          0.33477634+0.j,  0.55847663+0.j])),
 (1.6265878296869234,
  array([-0.85359916+0.j,  0.08043698+0.j,  0.34410988+0.j, -0.04021849+0.j,
          0.36647184+0.j,  0.10279894+0.j]))]

In [ ]:
# 读取zip压缩文件中的数据
file = ZipFile('./data_sets/Mnist/mnist_test.zip')
fr = file.open('mnist_test.csv')
train_data = pd.read_csv(fr, sep=",", header=None)
train_data.head()